### ISSUE TITLE
some problems encountered while learning the tutorial

### ISSUE THREAD

**Issue by TBetterman** [meco-group/gilc#1]
when i run b_tutorial1.m, error occurs:
Class gilc does not have a constant property or static method named 'nlpproblem'。

error gilc/control (line 59)
      constep = gilc.nlpproblem(2, this.nu, this.na, this.nx, this.nxa, this.ny);

error b_tutorial1 (line 82)
[ilc, u_i, ~] = ilc.control(a_i);    % Solve the control step for the first trial

**Comment by asteinh** [comment]
I cannot reproduce this error running the examples. It sounds like the gilc package `+gilc` is not on your path (anymore), so Matlab tries to access `nlpproblem` in the `gilc` class (which does not exist).

Make sure you either don't change directories when running the code (thus, stay in `gilc/matlab/examples`) or add the folder containing `+gilc` to your Matlab path (as an absolute path, so you can remove the `addpath('../')` in the beginning of the example files).

Does this help?

**Note** that gILC is not developed anymore - have a look at [RoFaLT](https://gitlab.mech.kuleuven.be/meco-software/rofalt), which is the actively developed follow-up software with extended capabilities.
